### ISSUE TITLE
Problemas de backend

### ISSUE THREAD

**Issue by aotaduy** [AgostinaChiara/tpDSW#3]
![imagen](https://github.com/AgostinaChiara/tpDSW/assets/11633046/08ccd4f1-efe4-4907-a4ea-56a9608a3e5a)
dist y node_modules no se suben al repo deberian estar enel gitignore

https://github.com/AgostinaChiara/tpDSW/blob/9d004f9981be080324f488eac29893570d3d1de3/backend/src/controllers/book.ts#L82C1-L82C67
En el response no estan bien los status de error o de exito 
pasa lo mismo en el update book deberian usar codigos http apropiados

/[backend](https://github.com/AgostinaChiara/tpDSW/tree/main/backend)/[src](https://github.com/AgostinaChiara/tpDSW/tree/main/backend/src)/[controllers](https://github.com/AgostinaChiara/tpDSW/tree/main/backend/src/controllers)
Pasa lo mismo en otros controllers para el caso de las creactiones y updates tienen que especificar codifos de error apropiados

https://github.com/AgostinaChiara/tpDSW/blob/9d004f9981be080324f488eac29893570d3d1de3/backend/src/controllers/user.ts#L66C5-L66C5

Veo que generan un token pero para que lo usan?

En la parte de CORS
backend/src/middlewares/cors.js

los origenes aceptados son todos localhost, deberiamos tener algo en el .env que se pueda tomar para un deploy real 

https://github.com/AgostinaChiara/tpDSW/blob/9d004f9981be080324f488eac29893570d3d1de3/backend/src/models/book.ts#L31

En nlos modelos deberiamos usar una relacion en vez de tener solo el Id de la entidad relacionada
podriamos usar https://sequelize.org/docs/v6/core-concepts/assocs/

backend/src/models/server.ts
esto deberia ir en el raiz asi se ve mas claro no es estrictamente un modelo sino mas bien la app
la convencion es ponerle app o server pero no como modelo

**Comment by AgostinaChiara** [comment]
Ya arreglamos el problema de los response y el CORS.
En los modelos usamos la asociación BelongsTo, osea, un libro pertenece a una categoría.
También solucionamos el problema de las carpetas del backend de dist y node_modules.
Por último lo del token lo utilizamos en la parte del front, tpDSW\frontend\src\app\utils\add-token.interceptor.ts , hay un interceptor, que es para que solo permita navegar a ciertas rutas solo si iniciaron sesión.

**Comment by aotaduy** [comment]
Buenisimo, lo del tokjen no pense que estaba suelto ahi veo que esta dentro de la funcion.

Si ya esta todo cerremos este issue.
